
extern zend_class_entry *beanspeak_connection_connectionawareinterface_ce;

ZEPHIR_INIT_CLASS(Beanspeak_Connection_ConnectionAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_beanspeak_connection_connectionawareinterface_setconnection, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, connection, Beanspeak\\Connection\\ConnectionInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(beanspeak_connection_connectionawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Beanspeak_Connection_ConnectionAwareInterface, getConnection, NULL)
	PHP_ABSTRACT_ME(Beanspeak_Connection_ConnectionAwareInterface, setConnection, arginfo_beanspeak_connection_connectionawareinterface_setconnection)
	PHP_FE_END
};
