
extern zend_class_entry *beanspeak_dispatcher_dispatcherawareinterface_ce;

ZEPHIR_INIT_CLASS(Beanspeak_Dispatcher_DispatcherAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_beanspeak_dispatcher_dispatcherawareinterface_setdispatcher, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, dispatcher, Beanspeak\\Dispatcher\\DispatcherInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(beanspeak_dispatcher_dispatcherawareinterface_method_entry) {
	PHP_ABSTRACT_ME(Beanspeak_Dispatcher_DispatcherAwareInterface, setDispatcher, arginfo_beanspeak_dispatcher_dispatcherawareinterface_setdispatcher)
	PHP_ABSTRACT_ME(Beanspeak_Dispatcher_DispatcherAwareInterface, getDispatcher, NULL)
	PHP_FE_END
};
